### PR TITLE
use bundle install

### PR DESCRIPTION
**Pull request by pdebuyl**
Trying to fix the travis build

### CODE REVIEW

**Comment by rougier** [comment]
`rvm use 2.2`maybe ?

**Comment by pdebuyl** [comment]
I did not get the full rundown of the travis builds but with 2.3 it passes (2.2.2 at minimum was needed)

**Comment by pdebuyl** [comment]
PS: is the CI useful? It is not used to build the website.

**Comment by rougier** [comment]
It doesn't hurt either, no ?

**Comment by pdebuyl** [comment]
no no

**Comment by khinsen** [comment]
It does hurt, in the same way that bureaucracy hurts: it made @pdebuyl invest time on unproductive work.

**Comment by rougier** [comment]
So let's get rid of it ?

**Pull request merged**
