### PR TITLE
add Delsuc:2020

### PR DESCRIPTION
**Pull request by pdebuyl**

### CODE REVIEW

**Comment by pdebuyl** [comment]
should I generate the website also ?

**Comment by khinsen** [comment]
For now, only @rougier knows the magic incantations required for rebuilding the Web site.

**Comment by pdebuyl** [comment]
I had to install ruby "bundle" for whedon and "bundle exec jekyll build" appears to work on my laptop... Thanks for the merge

**Comment by rougier** [comment]
Oh good to know you managed to build the website. What version of ruby did you use ? I'm using rbenv/2.6.5 because newer versions did not work last time I checked

**Comment by pdebuyl** [comment]
I use debian with the stock ruby.

**Pull request merged**
