### PR TITLE
NEW: adding GH action to auto-deploy website updates

### PR DESCRIPTION
**Pull request by romain-jacob**
Hello there, 

I am running another journal, [JSys](jsys.org), for which I heavily reused the RescienceC website code. Thanks for having it open! 

I just setup a github action for our website to auto-deploy the website updates (rather than having to run the `publish.sh` script). 

Feel free to merge if you like the feature :-)

### CODE REVIEW

**Comment by rougier** [comment]
Wonderful ! I shoudl have done it a while ago...

**Comment by rougier** [comment]
Not really working so far. Can you check?

**Comment by romain-jacob** [comment]
It seems to be an issue with the building of the site by Jekyll. Does you site builds fine locally?

**Comment by rougier** [comment]
Yes, but I've a bunch of gems and I think I froze ruby version because it breaks with newer version (just remember). The puslish.sh script has all the code.

**Comment by romain-jacob** [comment]
The frozen ruby version might be the source of the issue. I suppose one needs to tell the building action which version to use. I don't have time to look into this now though.

**Comment by rougier** [comment]
Ok. I'll check on my side and removed the action in the meantime. Thanks again for the PR.

**Pull request merged**
