### PR TITLE
Update 2018-06-14-Bavard-Théro.md

### PR DESCRIPTION
**Pull request by oliviaguest**
Typo!

### CODE REVIEW

**Comment by heloisethero** [comment]
Dear @oliviaguest and @rougier, to address the typo, you just need to change the "bibliography.bib" here: https://github.com/ReScience-Archives/Bavard-Thero-2018/tree/master/article.

At the line 62, you have to replace this:
`author={Caz{\'e}, Romain D and van der Meer, Matthijs AA},`
by this:
`author={Caz{\'e}, Romain D and {van der Meer}, Matthijs AA},`

If you re-edit the article with Latex, these extra brackets will ensure that the original article will be correctly cited as "Cazé and van der Meer", instead of "Cazé and Meer" as it currently appears in the published version. 

Thank you :)

**Comment by oliviaguest** [comment]
@heloisethero thanks! Would it be possible for you to do a PR on the repo with the edited and compiled files present so you can make sure your final PDF is as you want it/as it should be, please? If you haven't done this before see: https://help.github.com/articles/creating-a-pull-request/

**Comment by heloisethero** [comment]
I only wanted to transmit you this information but I don't want to do a PR myself to change it. The rest of the final PDF is as it should be.

**Comment by oliviaguest** [comment]
It would be really helpful if you did do the PR. It's the same thing one does when an author goes through and corrects the proofs for a more traditional journal — but I can also do it myself in a month or so (conference travels) but not sooner. 😅

**Comment by heloisethero** [comment]
I understand, and I don't mind waiting.

**Pull request merged**
