### PR TITLE
Adding published articles from RC 2020

### PR DESCRIPTION
**Pull request by koustuvsinha**
Adding the published articles from [ML Reproducibility Challenge 2020](https://github.com/ReScience/RC-2020). This concludes the editorial process for this edition 🎉

### CODE REVIEW

**Comment by rougier** [comment]
Nice work ! Congratulations ! You did not add the an entry on the main page. Did you forget or should I dot it?

**Comment by koustuvsinha** [comment]
Feel free to add the entry in the main page :)

Thanks for the help and support!!

Best,
Koustuv

On May 28, 2021, at 12:51 PM, Nicolas P. Rougier ***@***.***> wrote:

﻿

Nice work ! Congratulations ! You did not add the an entry on the main page. Did you forget or should I dot it?

**Comment by rougier** [comment]
It's online ! By the way, did you also add articles to rescience.articles repo (I did not see any PR)

**Comment by koustuvsinha** [comment]
Sorry was AFK for a while! Yeah I have not added any PR yet, the articles reside on https://github.com/ReScience/RC-2020 in different branches. Would you like me to add them to articles as well? Didn't want to crowd the repository since we have one for our own, but let me know if you would like that, happy to do the same.

**Comment by rougier** [comment]
No, it's fine.  Too much work for you. And when we'll migrate, we'll need to update. As long as they are hosted on Zenodo, I think it's fine.

**Comment by rougier** [comment]
Last thing I need to do is to reverse the order of entries such that your editorial appears first.

**Comment by rougier** [comment]
No, your numbering is good. It's only the request from the jekyll source that need to sort them in reverse order. Not sure how to do that yet.

**Comment by koustuvsinha** [comment]
I noticed that I had attributed the same number to one of the articles. I have fixed it in the PR #99. Although that did not solve the issue when I test the website locally.

**Pull request merged**
